### ISSUE TITLE
The codes cannot be used!

### ISSUE THREAD

**Issue by cmc1023** [mphilli/English-to-IPA#10]
Hi ,

You codes cannot be installed with following error:

File "/usr/local/lib/python3.5/dist-packages/English_to_IPA-0.0.1-py3.5.egg/eng_to_ipa/transcribe.py", line 58
    c.execute(f"SELECT word, phonemes FROM dictionary WHERE word IN ({quest[:-2]})", words_in)
                                                                                  ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.5/dist-packages/English_to_IPA-0.0.1-py3.5.egg/eng_to_ipa/rhymes.py", line 17
    c.execute(f"SELECT word, phonemes FROM dictionary WHERE phonemes "
                                                                     ^
SyntaxError: invalid syntax

**Comment by mphilli** [comment]
You need to be using Python 3.6+, which supports f-strings. See [here](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498).
