### ISSUE TITLE
error

### ISSUE THREAD

**Issue by uncle2** [mphilli/English-to-IPA#13]
u did awesome work, but when i run the import then the error occur.  do u know why? thanks.

>>> import eng_to_ipa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eng_to_ipa\__init__.py", line 1, in <module>
    from .transcribe import *
  File "eng_to_ipa\transcribe.py", line 69
    asset.execute(f"SELECT word, phonemes FROM dictionary WHERE word IN ({quest[:-2]})", words_in)
                                                                                      ^
SyntaxError: invalid syntax

**Comment by mphilli** [comment]
This is a common issue. Format strings using `f""` require Python 3.6 or greater. 
I am considering changing the syntax here to be comptabile with older versions of Python.

**Comment by uncle2** [comment]
> This is a common issue. Format strings using `f""` require Python 3.6 or greater.
> I am considering changing the syntax here to be comptabile with older versions of Python.

OK, got it. Much thanks
