### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by j-j-kam** [mphilli/English-to-IPA#23]
Good day. I experience no problems with the installation or whatsoever, no errors. Actually, when I run the code, simply nothing happens. There isn't any output at all. What are the possible reasons for that?

**Comment by t-cool** [comment]
There may be a problem with the installation of dependent libraries, so why don't you use venv?

https://python.land/virtual-environments/virtualenv

**Comment by mphilli** [comment]
The code doesn't run anything by default. You would import it as a library and start calling its functions.
