### ISSUE TITLE
Conversion "ʌ"

### ISSUE THREAD

**Issue by ghost** [mphilli/English-to-IPA#27]
The ARPABET "AH" (such as "love", "cut", "hut") should be converted to "ʌ".
But seems mistakenly converted to "ə".
Could you check that?

**Comment by ghost** [comment]
The ARPABETs should be converted as follows:
ah0 -> ə
ah1 -> ʌ
But when find_stress() is applied, they both become "ah".
So, both of them are coverted to "ə" when applied the rule "ah : ə"in cmu_to_ipa().

**Comment by JeremyLegron** [comment]
I would also appreciate a fix for this as it affects many common words and can lead to confusions.
It seems that pull request #26 was related to this issue, but it has been closed.

**Comment by bk111** [comment]
> The ARPABETs should be converted as follows: ah0 -> ə ah1 -> ʌ But when find_stress() is applied, they both become "ah". So, both of them are coverted to "ə" when applied the rule "ah : ə"in cmu_to_ipa().

"love, to" are all wired. Is the bug from CMU dict or this module?

**Comment by mphilli** [comment]
This should be fixed.

"butter problem" now gives me "ˈbʌtər ˈprɑbləm" (note the ʌ and ə at the stressed/unstressed parts).
