### ISSUE TITLE
"love, to" are all wired. Is the bug from CMU dict or this module?

### ISSUE THREAD

**Issue by bk111** [mphilli/English-to-IPA#30]
please check and fix it if it's from the English-to-IPA.
if it's from CMU dict, can someone Email to CMU dict author?

**Comment by mphilli** [comment]
I don't understand this comment. What is the issue?

**Comment by bk111** [comment]
> I don't understand this comment. What is the issue?
before, I installed with "pip install eng_to_ipa", love is /ləv/, to is /tɪ/
today I installed with "Run python -m pip install . in the same directory as  setup.py", now it's ok. love is /lʌv/, to is /tu/

Did you upgrade and fix? or it's because of "install method". where can I find the update log?

**Comment by mphilli** [comment]
You can't install just using "pip install eng_to_ipa" you have to do it the setup.py way from a local download. 

Somebody made an old version of the package available via pip download but it wasn't me, I don't manage that and I don't know how to.
