### ISSUE TITLE
new function (ruby-rt-rp-html) request

### ISSUE THREAD

**Issue by bk111** [mphilli/English-to-IPA#31]
Can we add a new function on it with ruby-rt-rp tag to produce html code? then we can insert the code into html directly.
the ruby-rt-rp tag will align the phonics with its word.(https://github.com/dohliam/rubify)
for example:

```
Let's listen to  Fox  tell the story. I love you. I   am eating a peach. Sheep is here. Ship is here. Once   upon   a time. 
 lɛts ˈlɪsən  tu  fɑks tɛl   ðə ˈstɔri. aɪ lʌv   ju.  aɪ æm  ˈitɪŋ   ə   piʧ.        ʃip   ɪz  hir.    ʃɪp  ɪz   hir.   wʌns  əˈpɑn  ə taɪm.
```

**Comment by mphilli** [comment]
I think I'm comfortable just allowing this to be a very simple Python package that handles the raw IPA conversions. If you want to give the package extra functionalities like producing HTML code then I would suggest forking the project and making these implementations yourself.
