### ISSUE TITLE
AH should be ʌ not ə

### ISSUE THREAD

**Issue by paulvonhippel** [mphilli/English-to-IPA#32]
The short u in cup, which ARPABET renders as AH, should be ʌ in IPA. You have it as ə

**Comment by mphilli** [comment]
I'm getting kʌp using the convert function. Make sure you have the latest version downloaded, as an update was made recently.

**Comment by paulvonhippel** [comment]
Thanks for your reply! I have the latest version according to *pip*, but
I'm still getting *cup->kəp*
Let me show you exactly what I'm doing:
*> pip install eng_to_ipa*
Requirement already satisfied: eng_to_ipa in
c:\users\...\appdata\local\programs\python\python311\lib\site-packages
(0.0.2)
*> python.exe "test.py"*
kəp
where the contents of test.py are

*import eng_to_ipa as ipaprint(ipa.convert("cup"))*

Why am I not getting the same result as you?

Best,
Paul

**Comment by mphilli** [comment]
You have to follow the instructions in the readme by downloading the latest repository locally. I don't know who made the project available via pip download, but it wasn't me.

**Comment by paulvonhippel** [comment]
OK, I reinstalled it by running
 pip install git+https://github.com/mphilli/English-to-IPA
and now the problems I reported are gone!

By default, pip installs from PyPI.org. Would you like to update the version that's there?

**Comment by paulvonhippel** [comment]
I'm sorry, I gotta raise this again. For a few days **ipa.convert("CUP")** returned _kʌp_, as it should, but as of today it returns _kəp_ again. Is it possible this fix got reverted when you fixed something else?

I believe I'm using the latest version. On the command line I run.
```
pip uninstall eng_to_ipa
pip install eng_to_ipa git+https://github.com/mphilli/English-to-IPA
python test.py
```
where the contents of test.py are
```
import eng_to_ipa as ipa
print(ipa.convert("CUP"))
```
The return value printed is
`kəp`

**Comment by mphilli** [comment]
I'm getting kʌp. Make sure you are using the latest version.

**Comment by mphilli** [comment]
Added a test for testing schwa versions. Passes for me: 

```
self.assertEqual(transcribe.convert("The cup of butter caused a problem and now we're upset."),
                             "ðə kʌp ʌv ˈbʌtər kɑzd ə ˈprɑbləm ənd naʊ wir əpˈsɛt.")
```

test_schwa.py::TestConversion::test_schwa 

========================== 1 passed in 0.41 seconds ===========================

Process finished with exit code 0

**Comment by paulvonhippel** [comment]
Hm, the same test doesn't pass for me. We must be using different versions, even though I'm pulling the code straight from github. Is it possible the code you are testing is not synced with the code on github? What happens when you install eng_to_ipa exactly as I do, like this?
`pip install --upgrade eng_to_ipa git+https://github.com/mphilli/English-to-IPA`
And then run your test?

**Comment by mphilli** [comment]
The two are synced. The test was just pushed onto Github per the latest version.

**Comment by paulvonhippel** [comment]
I'm sorry, the version I am pulling from GitHub is not passing the test that you proposed. I am uninstalling the old version then upgrading to the new one:
```
PS > pip uninstall eng_to_ipa
PS C:\Users\ph3828> pip install --upgrade eng_to_ipa git+https://github.com/mphilli/English-to-IPA
```
Amid the output I see this:
`Resolved https://github.com/mphilli/English-to-IPA to commit fda784a9a27a4b3be7260debc130e33b55210f6a`

Is that the same commit that you're using?

Then I run your proposed sentence through eng_to_ipa.convert.
And the actual output is not the same as the expected output. Characters that should be ʌ are converted instead to ə:
```
Expected output: ðə kʌp ʌv ˈbʌtər kɑzd ə ˈprɑbləm ənd naʊ wir əpˈsɛt.
Actual output: ðə kəp əv ˈbətər kɔzd ə ˈprɑbləm ənd naʊ wɪr ˈəpˌsɛt.
```

**Comment by paulvonhippel** [comment]
Here's the output I'm getting from your test_schwa.py:
```
======================================================================
FAIL: test_schwa (__main__.TestConversion.test_schwa)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "g:\My Drive\Python projects\Open Source Phonics\Code\test_schwa.py", line 11, in test_schwa
    self.assertEqual(transcribe.convert("The cup of butter caused a problem and now we're upset."),
AssertionError: 'ðə kəp əv ˈbətər kɔzd ə ˈprɑbləm ənd naʊ wɪr ˈəpˌsɛt.' != 'ðə kʌp ʌv ˈbʌtər kɑzd ə ˈprɑbləm ənd naʊ wir əpˈsɛt.'    
- ðə kəp əv ˈbətər kɔzd ə ˈprɑbləm ənd naʊ wɪr ˈəpˌsɛt.

+ ðə kʌp ʌv ˈbʌtər kɑzd ə ˈprɑbləm ənd naʊ wir əpˈsɛt.
?     ^  ^    ^     ^                       ^    ^
```

**Comment by paulvonhippel** [comment]
As I mentioned, when I ran
`pip install --upgrade eng_to_ipa git+https://github.com/mphilli/English-to-IPA`
The output said:
`Resolved https://github.com/mphilli/English-to-IPA to commit fda784a9a27a4b3be7260debc130e33b55210f6a`
I've now confirmed that the first 7 characters of the commit identifier (fda784a) match the most recent commit identifier that I see on GitHub, which you committed 20 hours ago.

If the version you are testing at home is passing test_schwa.py, I have to conclude that it is not is not the version that you have committed to GitHub. Even though, as you say, they ought to be the same. 

May I suggest that instead of continuing to test your home version, you instead try to reproduce the problem that I'm reporting. Install the version from GitHub, like this:
```
PS > pip uninstall eng_to_ipa
PS C:\Users\ph3828> pip install --upgrade eng_to_ipa git+https://github.com/mphilli/English-to-IPA
```
And then run test_schwa.py. See if it passes, as you've reported, or if it fails, as I'm reporting.

Thanks for your patience!

**Comment by paulvonhippel** [comment]
Looking at the source code for your function cmu_to_ipa(), the symbols dictionary appears to map the ARPABET to IPA. I would expect to see an entry like "ah":"ʌ" but instead I see "q": "ʌ", which seems odd because there's no q in the ARPABET:
```
symbols = {
    "a": "ə",
    "ey": "eɪ",
    "aa": "ɑ",
    "ae": "æ",
    "+": "ə",
    "ao": "ɔ",
    "q": "ʌ",
    "aw": "aʊ",
    "ay": "aɪ",
    "ch": "ʧ",
    "dh": "ð",
    "eh": "ɛ",
    "er": "ər",
    "hh": "h",
    "ih": "ɪ",
    "jh": "ʤ",
    "ng": "ŋ",
    "ow": "oʊ",
    "oy": "ɔɪ",
    "sh": "ʃ",
    "th": "θ",
    "uh": "ʊ",
    "uw": "u",
    "zh": "ʒ",
    "iy": "i",
    "y": "j"
}

```
Again I'm referring to the most recent GitHub commit [here](https://github.com/mphilli/English-to-IPA/blob/9fa37ad80ed1de3d61af21a321766b12634dcd68/eng_to_ipa/syllables.py), which may not be the version you're running in your kitchen. ;)

**Comment by mphilli** [comment]
`q` is used as a surrogate for ah1 while `+` is used as a surrogate for ah0. There are not other situations where distinct numberings need to correspond to unique IPA symbols. However, the symbol keys cannot contain numbers, as they get stripped during the handling of stress. This shouldn't impact results, as the symbol_dict is not accessible outside the function.

**Comment by paulvonhippel** [comment]
OK, that make sense. Nevertheless, the code on GitHub is converting cup to kəp instead of kʌp. Do let me know when you figure that out. I suspect the version you are testing is not synced with the version in GitHub, for whatever reason.

**Comment by mphilli** [comment]
There is nothing to resolve unfortunately. I've just tested it again (from Github) and I am getting the proper result. I don't have any proposed solutions for your continued issues.

**Comment by paulvonhippel** [comment]
Hm, I wonder what explains the difference between your result and mine. 
Is there a dependency I should be looking at?
