### ISSUE TITLE
"and" is translated incorrectly

### ISSUE THREAD

**Issue by paulvonhippel** [mphilli/English-to-IPA#33]
The call 
print(ipa.convert("and"))
returns
ənd
which is incorrect. It should return 
ænd

**Comment by paulvonhippel** [comment]
I'm using the version of eng_to_ipa that's published here on github, which I believe is the latest version.

**Comment by mphilli** [comment]
This project relies on the CMU phonetic dictionary for IPA translations, and according to them, "ənd" is a valid result for "and". To find all possible IPA conversions, use "retrieve_all=True" in the convert function to get the one you want.
