### ISSUE TITLE
How do you install it?

### ISSUE THREAD

**Issue by Qwerty-Space** [mphilli/English-to-IPA#6]
There's no setup.py

**Comment by mphilli** [comment]
A setup.py was just added, maybe that will help.

**Comment by Qwerty-Space** [comment]
Sweet, thanks!

**Comment by Jayboon** [comment]
i am trying to install but there is error msg
couldn't find the version that satisfies the requirement english_to_ipa(version:)
not matching distribution found for englsih_to_ipa
can any one help?
