### ISSUE TITLE
Import issue, please help

### ISSUE THREAD

**Issue by NAM-hj** [mphilli/English-to-IPA#9]
Hello, 

I try to set up this English-to-IPA but I get many error message
It would be very very appreciated to get your help to install.

I try
1. sudo python setup.py install  :  in the English-to-IPA-master folder
2. sudo python setup.py build  :  in the English-to-IPA-master folder
sudo python setup.py install  :  in the English-to-IPA-master folder
3. No any build or install  and do it in the English-to-IPA-master folder

both results give same error message
-----------------------------------------------------------------------------------------------------
(IN the English-to-IPA folder, i type python and do this...)
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import eng_to_ipa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eng_to_ipa/__init__.py", line 1, in <module>
    from .transcribe import *
  File "eng_to_ipa/transcribe.py", line 58
    c.execute(f"SELECT word, phonemes FROM dictionary WHERE word IN ({quest[:-2]})", words_in)
                                                                                  ^
SyntaxError: invalid syntax
-----------------------------------------------------------------------------------------------------

I'm very new at python, so I just comment and put
c.execute(words_in)
and try the same process.

Then I get this error message.
-----------------------------------------------------------------------------------------------------
>>> import eng_to_ipa as es
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eng_to_ipa/__init__.py", line 1, in <module>
    from .transcribe import *
  File "eng_to_ipa/transcribe.py", line 4, in <module>
    import eng_to_ipa.stress as stress
  File "eng_to_ipa/stress.py", line 25
SyntaxError: Non-ASCII character '\xcb' in file eng_to_ipa/stress.py on line 25, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
-----------------------------------------------------------------------------------------------------
I can see the symbols looks like " , " & " ' "
, so I just replace it as comma and quotes.

Then I get this error message.
-----------------------------------------------------------------------------------------------------
>>> import eng_to_ipa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eng_to_ipa/__init__.py", line 1, in <module>
    from .transcribe import *
  File "eng_to_ipa/transcribe.py", line 4, in <module>
    import eng_to_ipa.stress as stress
  File "eng_to_ipa/stress.py", line 4, in <module>
    import eng_to_ipa.syllables as syllables
  File "eng_to_ipa/syllables.py", line 4, in <module>
    from eng_to_ipa import transcribe
ImportError: cannot import name transcribe
-----------------------------------------------------------------------------------------------------

**Comment by formigone** [comment]
@nambee I'm able to import/install this repo directly with `pip`:

```
pip install git+https://github.com/mphilli/English-to-IPA.git
```

Hope that helps. Cheers!

**Comment by AlexRiina** [comment]
The line that's erroring out in the first stack trace is an f-string which is a python 3.7 feature and you're using python 2.7

**Comment by AlexRiina** [comment]
The second error is also coming due to using python 2 instead of python 3, though this one's not as particular about the version.

**Comment by AntonOfTheWoods** [comment]
> The line that's erroring out in the first stack trace is an f-string which is a python 3.7 feature and you're using python 2.7

In case some reads this, you can actually use f-strings since 3.6 (https://www.python.org/dev/peps/pep-0498/). I mention this because lots of Linux distributions still have 3.6 as the default python3.
